spring.application.name=Reto1
server.port=8080

# H2 embebida (simple, sin instalar nada extra)
spring.datasource.url=jdbc:h2:file:./data/empleadosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Para devolver 404 en rutas/métodos no definidos
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
